---
name: Integration tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        test: [libssh, httpd, bind]
    name: ${{ matrix.test }}
    container: fedora:rawhide
    env:
      PKCS11_MODULE: /usr/lib64/ossl-modules/pkcs11.so
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Build Requirements
        run: |
          dnf -y install git autoconf autoconf-archive automake libtool \
            openssl-devel
      - name: Setup, Build and Install pkcs11-provider
        run: |
          autoreconf -fiv
          ./configure --libdir=/usr/lib64
          make
          make install
      - name: Test
        run: |
          pushd tests/integration
          bash -e ${{ matrix.test }}.sh
